### ISSUE TITLE
Weight graph problem for children with over 5 years records 

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-growth-monitoring#14]
![image](https://user-images.githubusercontent.com/13656416/31068127-3bcf49c0-a75f-11e7-959c-e274388b9cf0.png)

**Comment by cagulas** [comment]
I am still seeing this issue in the V1.3.1 release. See dummy patient "John Rambo" with cagulas login. He is 5y old and the graph was normal until I entered a weight today, then it appeared like the above.

**Comment by ekigamba** [comment]
That was not fixed in this release. But I am about to conclude on it

**Comment by cagulas** [comment]
ah ok, I see that now. Thanks.

**Comment by ekigamba** [comment]
Should we discard weights recorded when the child is over 5 years old since such weights don't have a Z-Score?

**Comment by cagulas** [comment]
Ah I see, is that what is causing the issue? I might need to discuss with the PATH team on this one. Recording the weight is probably still good, even if z-score can't be recorded. Let me ask.

**Comment by cagulas** [comment]
After discussion, let's allow the weights for over 5 children to still be recorded. The z-score can't be recorded, so the z-score column can be left blank and the weight chart does not need to be updated.

**Comment by ekigamba** [comment]
Cool

**Comment by cagulas** [comment]
Lgtm
